version: "3"

services:
  search-experience-test-flask:
    container_name: search-experience-test-flask
    build:
      context: ./search-experience-test-flask
      target: builder
      shm_size: '2gb'
    ports:
      - "127.0.0.1:5000:5000"
    stop_signal: SIGINT
    environment:
      - FLASK_SERVER_PORT=5000
      - REDIS_HOST=search-experience-test-redis
      - POSTGRES_HOST=search-experience-test-postgres
      - POSTGRES_DB=search_tests
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
    volumes:
      - ./search-experience-test-flask:/src
    networks:
      - internal
  search-experience-test-react:
    container_name: search-experience-test-react
    hostname: search-experience-test-react
    ports:
      - "127.0.0.1:3000:3000"
    build:
      context: ./search-experience-test-react
      dockerfile: Dockerfile
    tty: true
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
    volumes:
      - ./search-experience-test-react:/app
    networks:
      - internal
  search-experience-test-postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: search_tests
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - ./search-experience-test-postgres:/docker-entrypoint-initdb.d
    networks:
      - internal
  search-experience-test-lighthouse:
    build: ./search-experience-test-lighthouse
    depends_on:
      - search-experience-test-redis
      - search-experience-test-postgres
    environment:
      - REDIS_HOST=search-experience-test-redis
      - POSTGRES_HOST=search-experience-test-postgres
      - POSTGRES_DB=search_tests
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    networks:
      - internal
  search-experience-test-crawler:
    build: ./search-experience-test-crawler
    depends_on:
      - search-experience-test-redis
      - search-experience-test-postgres
    environment:
      - REDIS_HOST=search-experience-test-redis
      - POSTGRES_HOST=search-experience-test-postgres
      - POSTGRES_DB=search_tests
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    networks:
      - internal
  search-experience-test-search:
    build: ./search-experience-test-search
    depends_on:
      - search-experience-test-redis
      - search-experience-test-postgres
    environment:
      - REDIS_HOST=search-experience-test-redis
      - POSTGRES_HOST=search-experience-test-postgres
      - POSTGRES_DB=search_tests
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    networks:
      - internal
  search-experience-test-redis:
    image: redis:alpine
    ports:
      - "127.0.0.1:6379:6379"
    volumes:
      - ./search-experience-test-redis/redis.conf:/usr/local/etc/redis/redis.conf:ro
    networks:
      - internal
  search-experience-test-nginx:
    image: nginx:latest
    container_name: search-experience-test-nginx
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./search-experience-test-react/dist:/var/www/html/
      - ./search-experience-test-nginx:/etc/nginx/conf.d
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
    networks:
      - internal
      - external
networks:
  external:
    driver: bridge
  internal:
    driver: bridge