DROP TABLE IF EXISTS crawls;

CREATE TABLE crawls (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    name TEXT NOT NULL,
    requestURL TEXT NOT NULL,
	status INTEGER NOT NULL,
    page_data TEXT
);